services:
  discord-crypto-bot:
    build: .
    container_name: discord-crypto-screening-tool
    env_file: .env
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - custom_bridge
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: ["CMD", "nslookup", "google.com", "1.1.1.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  custom_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

  # discord-crypto-bot-2:
  #   build: .
  #   container_name: discord-crypto-screening-tool-2
  #   env_file: .env2
  #   volumes:
  #     - ./cache:/app/cache
  #   restart: unless-stopped
  #   privileged: true
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=0
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   networks:
  #     - custom_bridge
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128m
  #   healthcheck:
  #     test: ["CMD", "nslookup", "google.com", "1.1.1.1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s