services:
  discord-crypto-bot:
    build: .
    container_name: discord-crypto-screening-tool
    env_file: .env
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - custom_bridge
    healthcheck:
      test: ["CMD", "nslookup", "google.com", "1.1.1.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  custom_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

  # discord-crypto-bot-2:
  #   build: .
  #   container_name: discord-crypto-screening-tool-2
  #   env_file: .env2
  #   volumes:
  #     - ./bybit_pairs_cache.json:/app/bybit_pairs_cache.json
  #     - ./binance_pairs_cache.json:/app/binance_pairs_cache.json
  #     - ./bitget_pairs_cache.json:/app/bitget_pairs_cache.json
  #     - ./gate_pairs_cache.json:/app/gate_pairs_cache.json
  #   restart: unless-stopped
  #   dns:
  #     - 127.0.0.1
  #   networks:
  #     - custom_bridge
  #   healthcheck:
  #     test: ["CMD", "nslookup", "google.com", "127.0.0.1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s